name: CI for C++ Client and Server

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  cpp-build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download CMake
        run: choco install cmake

      - name: Build and test client
        run: |
          cmake -S ./client -B ./client/build
          cmake --build ./client/build
          cd ./client/build && ctest --output-on-failure

      - name: Build and test server
        run: |
          cmake -S ./server -B ./server/build
          cmake --build ./server/build
          cd ./server/build && ctest --output-on-failure